# config.py

TIMEFRAMES = {
    'Short_Term_Analysis': {'period': '6mo', 'interval': '1d'},
    'Medium_Term_Analysis': {'period': '2y', 'interval': '1d'},
    'Long_Term_Analysis': {'period': '5y', 'interval': '1wk'}
}

# TICKERS = [
#     'MSFT', 'NVDA', 'AAPL', 'AMZN', 'GOOGL', 'GOOG', 'META', 'AVGO', 'BRK-B', 'TSLA',
#     'WMT', 'JPM', 'LLY', 'V', 'MA', 'NFLX', 'ORCL', 'XOM', 'COST', 'PG','GE',


TICKERS = [
    'AAL', 'AAOI', 'AAON', 'AAPL', 'ABCB', 'ABEO', 'ABL', 'ABNB', 'ACAD',
    'ACB', 'ACDC', 'ACGL', 'ACHC', 'ACIC', 'ACIW', 'ACLS', 'ACLX', 'ACMR', 'ACT',
    'ACVA', 'ADBE', 'ADEA', 'ADI', 'ADMA', 'ADP', 'ADPT', 'ADSK', 'ADTN', 'ADUS',
    'AEHR', 'AEIS', 'AEP', 'AFRM', 'AGIO', 'AGNC', 'AGYS', 'AHCO', 'AIP', 'AIRS',
    'AKAM', 'AKRO', 'ALGM', 'ALGN', 'ALGT', 'ALHC', 'ALKS', 'ALKT', 'ALLT', 'ALNY',
    'ALRM', 'ALT', 'ALVO', 'AMAL', 'AMAT', 'AMBA', 'AMCX', 'AMD', 'AMED', 'AMGN',
    'AMKR', 'AMLX', 'AMPH', 'AMPL', 'AMRK', 'AMSC', 'AMWD', 'AMZN', 'ANAB', 'ANDE',
    'ANGI', 'ANGO', 'ANIP', 'ANSS', 'AOSL', 'APA', 'APEI', 'APGE', 'APLD', 'APLS',
    'APOG', 'APP', 'APPF', 'APPN', 'APPS', 'ARCB', 'ARCC', 'ARCT', 'ARGX', 'ARHS',
    'ARLP', 'ARM', 'ARQQ', 'ARQT', 'ARRY', 'ARVN', 'ARWR', 'ASML', 'ASND', 'ASO',
    'ASPI', 'ASTL', 'ASTS', 'ATAT', 'ATEC', 'ATRC', 'ATRO', 'ATSG', 'ATXS', 'AUPH',
    'AUR', 'AURA', 'AVAH', 'AVAV', 'AVDL', 'AVDX', 'AVGO', 'AVO', 'AVPT', 'AVT',
    'AVXL', 'AXGN', 'AXON', 'AXSM', 'AZN', 'AZTA', 'BAND', 'BANR', 'BASE', 'BATRK',
    'BBCP', 'BBIO', 'BBSI', 'BCPC', 'BCRX', 'BCYC', 'BEAM', 'BECN', 'BGC', 'BHF',
    'BIDU', 'BIGC', 'BIIB', 'BILI', 'BJRI', 'BKNG', 'BKR', 'BL', 'BLBD', 'BLFS',
    'BLKB', 'BLMN', 'BLZE', 'BMBL', 'BMRN', 'BNTX', 'BOKF', 'BPMC', 'BPOP', 'BRKL',
    'BRKR', 'BRZE', 'BSGM', 'BSY', 'BTDR', 'BUSE', 'BVS', 'BYRN', 'BZ', 'CAKE',
    'CALM', 'CAMT', 'CAPR', 'CAR', 'CARG', 'CART', 'CASH', 'CASY', 'CATY', 'CBRL',
    'CBSH', 'CCAP', 'CCCS', 'CCEP', 'CCOI', 'CCRN', 'CCSI', 'CDNA', 'CDNS', 'CDTX',
    'CDW', 'CECO', 'CEG', 'CELC', 'CELH', 'CENT', 'CENTA', 'CENX', 'CERT', 'CEVA',
    'CFFN', 'CFLT', 'CG', 'CGBD', 'CGEM', 'CGNT', 'CGNX', 'CHDN', 'CHEF', 'CHI',
    'CHKP', 'CHRD', 'CHRW', 'CHTR', 'CHW', 'CHX', 'CHY', 'CINF', 'CLBK', 'CLBT',
    'CLDX', 'CLMT', 'CLPT', 'CLSK', 'CMCO', 'CMCSA', 'CME', 'CMPO', 'CMPR', 'CMRX',
    'CNOB', 'CNTA', 'CNXC', 'COCO', 'COGT', 'COHU', 'COIN', 'COKE', 'COLB', 'COLL',
    'COLM', 'COMM', 'COO', 'COOP', 'CORT', 'COST', 'CPRT', 'CPRX', 'CRCT', 'CRDO',
    'CRESY', 'CRMD', 'CRNC', 'CRNX', 'CROX', 'CRSP', 'CRSR', 'CRTO', 'CRUS', 'CRWD',
    'CSCO', 'CSGP', 'CSGS', 'CSIQ', 'CSQ', 'CSTL', 'CSWC', 'CSX', 'CTAS', 'CTLP',
    'CTSH', 'CURI', 'CVBF', 'CVGW', 'CVLT', 'CWCO', 'CWST', 'CYBR', 'CYRX', 'CYTK',
    'CZR', 'DAKT', 'DASH', 'DAVE', 'DAWN', 'DBX', 'DCOM', 'DCTH', 'DDOG', 'DGII',
    'DIOD', 'DKNG', 'DLO', 'DLTR', 'DMRC', 'DNLI', 'DNTH', 'DOCU', 'DOGZ', 'DOMO',
    'DOOO', 'DORM', 'DOX', 'DRS', 'DRVN', 'DSGX', 'DSP', 'DUOL', 'DVAX', 'DVY',
    'DXCM', 'DYN', 'EA', 'EBAY', 'EBC', 'ECPG', 'EEFT', 'EEMA', 'EFSC', 'EGBN',
    'EH', 'ELVN', 'EMBC', 'ENPH', 'ENSG', 'ENTG', 'ENVX', 'EOLS', 'EQIX', 'ERIC',
    'ERII', 'ESTA', 'ETNB', 'ETON', 'ETSY', 'EVCM', 'EVER', 'EVLV', 'EVRG', 'EWBC',
    'EWCZ', 'EWTX', 'EXAS', 'EXC', 'EXEL', 'EXLS', 'EXPD', 'EXPE', 'EXPI', 'EXPO',
    'EXTR', 'EYE', 'EYPT', 'EZPW', 'FA', 'FANG', 'FARO', 'FAST', 'FBNC', 'FCFS',
    'FDUS', 'FELE', 'FFBC', 'FFIC', 'FFIN', 'FFIV', 'FHB', 'FIBK', 'FIP', 'FISI',
    'FITB', 'FIVE', 'FIVN', 'FIZZ', 'FLEX', 'FLGT', 'FLWS', 'FLYW', 'FOLD', 'FORM',
    'FOX', 'FOXA', 'FOXF', 'FRME', 'FROG', 'FRPT', 'FRSH', 'FSLR', 'FTAI', 'FTDR',
    'FTNT', 'FTRE', 'FULC', 'FULT', 'FUTU', 'FWONK', 'FWRD', 'FWRG', 'FYBR', 'GAMB',
    'GBDC', 'GCMG', 'GCT', 'GDEN', 'GDS', 'GDYN', 'GEHC', 'GEN', 'GFS', 'GGAL',
    'GH', 'GHRS', 'GIII', 'GILD', 'GILT', 'GLBE', 'GLDD', 'GLNG', 'GLPG', 'GLPI',
    'GLUE', 'GMAB', 'GNTX', 'GO', 'GOGL', 'GOGO', 'GOOD', 'GOOG', 'GOOGL', 'GPCR',
    'GRFS', 'GRPN', 'GRRR', 'GSHD', 'GT', 'GTLB', 'GTX', 'HAFC', 'HALO', 'HAS',
    'HBAN', 'HBNC', 'HCKT', 'HCSG', 'HDSN', 'HEES', 'HELE', 'HFWA', 'HIMX', 'HLIT',
    'HLMN', 'HLNE', 'HNRG', 'HOLX', 'HON', 'HONE', 'HOOD', 'HOPE', 'HPK', 'HQY',
    'HRMY', 'HROW', 'HRZN', 'HSAI', 'HSIC', 'HST', 'HSTM', 'HTBK', 'HTHT', 'HTLD',
    'HTZ', 'HUBG', 'HURN', 'HUT', 'HWC', 'IAC', 'IART', 'IAS', 'IBB', 'IBEX',
    'IBKR', 'IBOC', 'ICFI', 'ICHR', 'ICLR', 'ICUI', 'IDCC', 'IDXX', 'IDYA', 'IEF',
    'IEP', 'IESC', 'IIIV', 'IJT', 'ILMN', 'IMCR', 'IMNM', 'IMTX', 'IMVT', 'IMXI',
    'INCY', 'INDB', 'INDV', 'INMD', 'INOD', 'INSM', 'INTA', 'INTC', 'INTR', 'INTU',
    'INVA', 'IONS', 'IOSP', 'IPAR', 'IPGP', 'IRDM', 'IREN', 'IRON', 'IRTC', 'ISRG',
    'ITOS', 'ITRI', 'IUSG', 'IUSV', 'JACK', 'JAMF', 'JANX', 'JAZZ', 'JBHT', 'JD',
    'JFIN', 'JKHY', 'KALU', 'KALV', 'KC', 'KDP', 'KE', 'KELYA', 'KFRC', 'KHC',
    'KLAC', 'KLIC', 'KNSA', 'KRNT', 'KRNY', 'KROS', 'KRUS', 'KRYS', 'KTOS', 'KURA',
    'KYMR', 'LAMR', 'LANC', 'LAND', 'LASR', 'LAUR', 'LBAI', 'LBRDA', 'LBRDK', 'LBTYA',
    'LBTYK', 'LECO', 'LEGN', 'LFMD', 'LFST', 'LFUS', 'LGIH', 'LI', 'LILA', 'LILAK',
    'LINC', 'LIND', 'LITE', 'LIVN', 'LKFN', 'LKQ', 'LLYVA', 'LLYVK', 'LMAT', 'LMB',
    'LNT', 'LNTH', 'LNW', 'LOCO', 'LOGI', 'LOPE', 'LOVE', 'LPLA', 'LQDA', 'LQDT',
    'LRCX', 'LSCC', 'LSEA', 'LSTR', 'LTBR', 'LULU', 'LUNR', 'LX', 'LYFT', 'LZ',
    'MAMA', 'MANH', 'MAR', 'MARA', 'MASI', 'MAT', 'MATW', 'MBIN', 'MBLY', 'MBUU',
    'MCHP', 'MDB', 'MDGL', 'MDLZ', 'MDXG', 'MEDP', 'MELI', 'MEOH', 'MESO', 'META',
    'METC', 'MFIC', 'MGNI', 'MGPI', 'MGTX', 'MIDD', 'MIRM', 'MITK', 'MKSI', 'MKTX',
    'MLCO', 'MLKN', 'MLTX', 'MLYS', 'MMSI', 'MMYT', 'MNDY', 'MNMD', 'MNRO', 'MNST',
    'MOMO', 'MORN', 'MPWR', 'MQ', 'MRCY', 'MRNA', 'MRTN', 'MRUS', 'MRVL', 'MSEX',
    'MSFT', 'MSTR', 'MTCH', 'MTLS', 'MTRX', 'MTSI', 'MU', 'MXL', 'MYGN', 'MYRG',
    'NAMS', 'NAVI', 'NBIX', 'NBTB', 'NCMI', 'NCNO', 'NDAQ', 'NDSN', 'NEO', 'NEOG',
    'NETD', 'NEXT', 'NFBK', 'NFLX', 'NICE', 'NMFC', 'NMIH', 'NMRK', 'NN', 'NNOX',
    'NOVT', 'NPCE', 'NRDS', 'NRIX', 'NSIT', 'NSSC', 'NTAP', 'NTCT', 'NTES', 'NTGR',
    'NTLA', 'NTNX', 'NTRA', 'NTRS', 'NUVL', 'NVAX', 'NVCR', 'NVDA', 'NVEE', 'NVMI',
    'NVTS', 'NWBI', 'NWE', 'NWL', 'NWS', 'NWSA', 'NXPI', 'NXST', 'NXT', 'NYMT',
    'OCFC', 'OCSL', 'OCUL', 'ODD', 'ODFL', 'ODP', 'OFIX', 'OKTA', 'OLED', 'OLLI',
    'OM', 'OMCL', 'ON', 'ONB', 'ONEQ', 'OPCH', 'OPRA', 'OPRT', 'ORIC', 'ORLY',
    'ORRF', 'OSBC', 'OSIS', 'OSPN', 'OST', 'OSW', 'OTEX', 'OTTR', 'OZK', 'PAA',
    'PAGP', 'PAHC', 'PANW', 'PARA', 'PATK', 'PAX', 'PAYO', 'PAYX', 'PBPB', 'PCAR',
    'PCH', 'PCRX', 'PCT', 'PCTY', 'PCVX', 'PDCO', 'PDD', 'PDFS', 'PECO', 'PEGA',
    'PENN', 'PEP', 'PERI', 'PEY', 'PFF', 'PFG', 'PGNY', 'PGY', 'PHAT', 'PI',
    'PINC', 'PLAB', 'PLAY', 'PLMR', 'PLSE', 'PLUS', 'PLXS', 'PLYA', 'PNFP', 'PNTG',
    'PODD', 'POOL', 'POWI', 'POWL', 'PPBI', 'PPC', 'PPH', 'PPTA', 'PRAA', 'PRAX',
    'PRCH', 'PRCT', 'PRDO', 'PRGS', 'PRTH', 'PRVA', 'PSMT', 'PSNL', 'PTC', 'PTCT',
    'PTEN', 'PTGX', 'PTLO', 'PTON', 'PUBM', 'PWP', 'PYCR', 'PYPL', 'PZZA', 'QCOM',
    'QDEL', 'QFIN', 'QLYS', 'QNST', 'QQQ', 'QQQX', 'QRVO', 'QSG', 'QUBT', 'QURE',
    'RARE', 'RCAT', 'RDFN', 'RDNT', 'RDUS', 'RDWR', 'REAL', 'REG', 'REGN', 'RELY',
    'REPL', 'REYN', 'RGC', 'RGEN', 'RGLD', 'RGLS', 'RGNX', 'RGTI', 'RIGL', 'RING',
    'RIOT', 'RIVN', 'RKLB', 'RMBS', 'RNA', 'RNST', 'RNW', 'ROAD', 'ROCK', 'ROIV',
    'ROKU', 'ROOT', 'ROP', 'ROST', 'RPAY', 'RPD', 'RPRX', 'RRR', 'RUM', 'RUN',
    'RUSHA', 'RVMD', 'RWAY', 'RXRX', 'RXST', 'RYAAY', 'RYTM', 'SAGE', 'SAIA', 'SANM',
    'SATS', 'SBAC', 'SBCF', 'SBET', 'SBGI', 'SBLK', 'SBRA', 'SBUX', 'SCHL', 'SCSC',
    'SCVL', 'SDGR', 'SEDG', 'SEIC', 'SEZL', 'SFM', 'SFNC', 'SGML', 'SGRY', 'SHBI',
    'SHC', 'SHEN', 'SHLS', 'SHOO', 'SHY', 'SHYF', 'SIBN', 'SIGA', 'SIGI', 'SIMO',
    'SIRI', 'SITM', 'SKWD', 'SKYT', 'SKYW', 'SLAB', 'SLM', 'SLNO', 'SLP', 'SLRC',
    'SMCI', 'SMH', 'SMLR', 'SMMT', 'SMPL', 'SMTC', 'SNCY', 'SNDX', 'SNEX', 'SNPS',
    'SNY', 'SOFI', 'SONO', 'SOUN', 'SOXX', 'SPNS', 'SPRY', 'SPSC', 'SPT', 'SPTN',
    'SRAD', 'SRCL', 'SRPT', 'SRRK', 'SSB', 'SSNC', 'SSRM', 'SSYS', 'STAA', 'STBA',
    'STEP', 'STER', 'STGW', 'STKL', 'STLD', 'STNE', 'STOK', 'STRA', 'STRL', 'STX',
    'SUPN', 'SWBI', 'SWIM', 'SWKS', 'SWTX', 'SYM', 'SYNA', 'SZZL', 'TARS', 'TASK',
    'TATT', 'TBBK', 'TBPH', 'TCBI', 'TCOM', 'TCPC', 'TDUP', 'TEAM', 'TECH', 'TENB',
    'TER', 'TFIN', 'TFSL', 'TGTX', 'TH', 'THRM', 'THRY', 'TIGO', 'TIGR', 'TILE',
    'TIPT', 'TITN', 'TKNO', 'TLT', 'TMCI', 'TMDX', 'TMUS', 'TNDM', 'TOWN', 'TPG',
    'TREE', 'TRIN', 'TRIP', 'TRMB', 'TRMD', 'TRMK', 'TROW', 'TRS', 'TRUP', 'TRVI',
    'TSCO', 'TSEM', 'TSLA', 'TTD', 'TTEK', 'TTGT', 'TTMI', 'TTWO', 'TUR', 'TVTX',
    'TW', 'TWST', 'TXG', 'TXN', 'TXRH', 'TYRA', 'UAL', 'UBSI', 'UCTT', 'UDMY',
    'UFPI', 'UFPT', 'ULTA', 'UMBF', 'UPBD', 'UPST', 'UPWK', 'UPXI', 'URBN', 'URGN',
    'UTHR', 'VBTX', 'VC', 'VCEL', 'VCTR', 'VCYT', 'VECO', 'VEON', 'VERA', 'VERV',
    'VERX', 'VIAV', 'VICR', 'VIGL', 'VIR', 'VIRT', 'VITL', 'VKTX', 'VLY', 'VNET',
    'VNOM', 'VOD', 'VRDN', 'VREX', 'VRNA', 'VRNS', 'VRNT', 'VRRM', 'VRSK', 'VRSN',
    'VRTX', 'VSAT', 'VSEC', 'VSTM', 'VTRS', 'WABC', 'WAFD', 'WASH', 'WB', 'WBA',
    'WBD', 'WDAY', 'WDC', 'WEN', 'WERN', 'WEST', 'WFRD', 'WGS', 'WING', 'WIX',
    'WMG', 'WSBC', 'WSC', 'WSFS', 'WTFC', 'WTW', 'WVE', 'WWD', 'WYNN', 'XEL',
    'XENE', 'XMTR', 'XNCR', 'XNET', 'XP', 'XPEL', 'XRAY', 'XRX', 'Z', 'ZBRA',
    'ZD', 'ZG', 'ZI', 'ZION', 'ZLAB', 'ZM', 'ZS', 'ZVRA', 'ZYME'
]